Repository Thomas-59/Carto, pull requests merged in 2025-01, with the labels that each got.

#30 :bug: fix return to initPage + fix seek email already exist in bdd
  Mobile/Carto/lib/carto_app.dart
  Mobile/Carto/lib/data_manager.dart
  Mobile/Carto/lib/views/pages/filter_page.dart
  Mobile/Carto/lib/views/pages/home_page.dart
  Mobile/Carto/lib/views/pages/init_page.dart
  Mobile/Carto/lib/views/pages/signup_page.dart
  Mobile/Carto/lib/views/widgets/form/form_fields/mail_form_field.dart
Labels: bug

#33 :bug: fix forgotten password web page + fix seek username already exi…
  Back/carto/src/main/resources/templates/ResetPassword.html
  Mobile/Carto/lib/views/widgets/form/form_fields/username_form_field.dart
Labels: bug

#36 fix(manager information) : new line in database when updating account data
  Back/carto/src/main/java/fr/univ/carto/service/AccountService.java
  Mobile/Carto/lib/cubit/location_cubit.dart
  Mobile/Carto/lib/views/pages/account_page.dart
  Mobile/Carto/lib/views/pages/home_page.dart
  Mobile/Carto/lib/views/pages/init_page.dart
  Mobile/Carto/lib/views/pages/login_page.dart
  Mobile/Carto/lib/views/pages/signup_page.dart
  Mobile/Carto/lib/views/widgets/form/account_form.dart
  Mobile/Carto/lib/views/widgets/form/form_fields/manager_information_form_field.dart
  Mobile/Carto/lib/views/widgets/map_widget.dart
Labels: bug, enhancement

#37 Fix smtp
  Back/carto/src/main/java/fr/univ/carto/utils/EmailSender.java
Labels: bug

#38 Apply hot fix on dev
  .github/workflows/release.yml
  Back/carto/src/main/java/fr/univ/carto/service/AccountService.java
  Back/carto/src/main/java/fr/univ/carto/utils/EmailSender.java
  Back/carto/src/main/resources/templates/ResetPassword.html
  Mobile/Carto/android/app/src/main/AndroidManifest.xml
  Mobile/Carto/android/app/src/main/res/xml/network_security_config.xml
  Mobile/Carto/lib/cubit/location_cubit.dart
  Mobile/Carto/lib/data_manager.dart
  Mobile/Carto/lib/views/pages/account_page.dart
  Mobile/Carto/lib/views/pages/establishement_details_page.dart
  Mobile/Carto/lib/views/pages/filter_page.dart
  Mobile/Carto/lib/views/pages/forgotten_password_page.dart
  Mobile/Carto/lib/views/pages/home_page.dart
  Mobile/Carto/lib/views/pages/init_page.dart
  Mobile/Carto/lib/views/pages/login_page.dart
  Mobile/Carto/lib/views/pages/signup_page.dart
  Mobile/Carto/lib/views/widgets/buttons.dart
  Mobile/Carto/lib/views/widgets/form/account_form.dart
  Mobile/Carto/lib/views/widgets/form/form_fields/manager_information_form_field.dart
  Mobile/Carto/lib/views/widgets/form/form_fields/username_form_field.dart
  Mobile/Carto/lib/views/widgets/form/other_fields/hour_piker.dart
  Mobile/Carto/lib/views/widgets/map_widget.dart
Labels: bug

#39 Clean code 01/2025
  Mobile/Carto/lib/Exceptions/bad_credential_exception.dart
  Mobile/Carto/lib/carto_app.dart
  Mobile/Carto/lib/data_manager.dart
  Mobile/Carto/lib/enum/day_of_the_week_enum.dart
  Mobile/Carto/lib/enum/game_type_enum.dart
  Mobile/Carto/lib/enum/price_enum.dart
  Mobile/Carto/lib/enum/query_enum.dart
  Mobile/Carto/lib/enum/role_enum.dart
  Mobile/Carto/lib/main.dart
  Mobile/Carto/lib/models/account.dart
  Mobile/Carto/lib/models/establishment.dart
  Mobile/Carto/lib/models/establishment_data.dart
  Mobile/Carto/lib/services/account_service.dart
  Mobile/Carto/lib/services/address_service.dart
  Mobile/Carto/lib/services/establishment_service.dart
  Mobile/Carto/lib/services/location_service.dart
  Mobile/Carto/lib/utils/establishment_games.dart
  Mobile/Carto/lib/utils/intent_utils/intent_utils.dart
  Mobile/Carto/lib/utils/opening_hours.dart
  Mobile/Carto/lib/viewmodel/account_view_model.dart
  Mobile/Carto/lib/viewmodel/address_view_model.dart
  Mobile/Carto/lib/viewmodel/establishment_view_model.dart
  Mobile/Carto/lib/views/pages/account_page.dart
  Mobile/Carto/lib/views/pages/address_input_page.dart
  Mobile/Carto/lib/views/pages/establishement_details_page.dart
  Mobile/Carto/lib/views/pages/filter_page.dart
  Mobile/Carto/lib/views/pages/forgotten_password_page.dart
  Mobile/Carto/lib/views/pages/home_page.dart
  Mobile/Carto/lib/views/pages/login_page.dart
  Mobile/Carto/lib/views/pages/manage_page.dart
  Mobile/Carto/lib/views/pages/search_page.dart
  Mobile/Carto/lib/views/pages/signup_page.dart
  Mobile/Carto/lib/views/pages/suggestion_page.dart
  Mobile/Carto/lib/views/pages/thanking_page.dart
  Mobile/Carto/lib/views/widgets/accordeons.dart
  Mobile/Carto/lib/views/widgets/buttons.dart
  Mobile/Carto/lib/views/widgets/filter_tag.dart
  Mobile/Carto/lib/views/widgets/form/account_form.dart
  Mobile/Carto/lib/views/widgets/form/contact_form.dart
  Mobile/Carto/lib/views/widgets/form/form_fields/double_password_form_field.dart
  Mobile/Carto/lib/views/widgets/form/form_fields/mail_form_field.dart
  Mobile/Carto/lib/views/widgets/form/form_fields/manager_information_form_field.dart
  Mobile/Carto/lib/views/widgets/form/form_fields/my_form_field.dart
  Mobile/Carto/lib/views/widgets/form/form_fields/my_form_field_double.dart
  Mobile/Carto/lib/views/widgets/form/form_fields/my_form_field_http_link.dart
  Mobile/Carto/lib/views/widgets/form/form_fields/my_form_field_int.dart
  Mobile/Carto/lib/views/widgets/form/form_fields/my_form_field_mail.dart
  Mobile/Carto/lib/views/widgets/form/form_fields/single_password_form_field.dart
  Mobile/Carto/lib/views/widgets/form/form_fields/username_form_field.dart
  Mobile/Carto/lib/views/widgets/form/games_form.dart
  Mobile/Carto/lib/views/widgets/form/general_form.dart
  Mobile/Carto/lib/views/widgets/form/opening_hour_form.dart
  Mobile/Carto/lib/views/widgets/form/other_fields/game_counter.dart
  Mobile/Carto/lib/views/widgets/form/other_fields/hour_piker.dart
  Mobile/Carto/lib/views/widgets/form/other_fields/my_checkbox_list_tile.dart
  Mobile/Carto/lib/views/widgets/form/other_fields/price_button.dart
  Mobile/Carto/lib/views/widgets/map_widget.dart
  Mobile/Carto/lib/views/widgets/tags.dart
  Mobile/Carto/lib/views/widgets/text.dart
Labels: documentation

#40 Clean code 01/2025
  Mobile/Carto/lib/Exceptions/bad_credential_exception.dart
  Mobile/Carto/lib/carto_app.dart
  Mobile/Carto/lib/data_manager.dart
  Mobile/Carto/lib/enum/day_of_the_week_enum.dart
  Mobile/Carto/lib/enum/game_type_enum.dart
  Mobile/Carto/lib/enum/price_enum.dart
  Mobile/Carto/lib/enum/query_enum.dart
  Mobile/Carto/lib/enum/role_enum.dart
  Mobile/Carto/lib/main.dart
  Mobile/Carto/lib/models/account.dart
  Mobile/Carto/lib/models/establishment.dart
  Mobile/Carto/lib/models/establishment_data.dart
  Mobile/Carto/lib/services/account_service.dart
  Mobile/Carto/lib/services/address_service.dart
  Mobile/Carto/lib/services/establishment_service.dart
  Mobile/Carto/lib/services/location_service.dart
  Mobile/Carto/lib/utils/establishment_games.dart
  Mobile/Carto/lib/utils/intent_utils/intent_utils.dart
  Mobile/Carto/lib/utils/opening_hours.dart
  Mobile/Carto/lib/viewmodel/account_view_model.dart
  Mobile/Carto/lib/viewmodel/address_view_model.dart
  Mobile/Carto/lib/viewmodel/establishment_view_model.dart
  Mobile/Carto/lib/views/pages/account_page.dart
  Mobile/Carto/lib/views/pages/address_input_page.dart
  Mobile/Carto/lib/views/pages/establishement_details_page.dart
  Mobile/Carto/lib/views/pages/filter_page.dart
  Mobile/Carto/lib/views/pages/forgotten_password_page.dart
  Mobile/Carto/lib/views/pages/home_page.dart
  Mobile/Carto/lib/views/pages/login_page.dart
  Mobile/Carto/lib/views/pages/manage_page.dart
  Mobile/Carto/lib/views/pages/search_page.dart
  Mobile/Carto/lib/views/pages/signup_page.dart
  Mobile/Carto/lib/views/pages/suggestion_page.dart
  Mobile/Carto/lib/views/pages/thanking_page.dart
  Mobile/Carto/lib/views/widgets/accordeons.dart
  Mobile/Carto/lib/views/widgets/buttons.dart
  Mobile/Carto/lib/views/widgets/filter_tag.dart
  Mobile/Carto/lib/views/widgets/form/account_form.dart
  Mobile/Carto/lib/views/widgets/form/contact_form.dart
  Mobile/Carto/lib/views/widgets/form/form_fields/double_password_form_field.dart
  Mobile/Carto/lib/views/widgets/form/form_fields/mail_form_field.dart
  Mobile/Carto/lib/views/widgets/form/form_fields/manager_information_form_field.dart
  Mobile/Carto/lib/views/widgets/form/form_fields/my_form_field.dart
  Mobile/Carto/lib/views/widgets/form/form_fields/my_form_field_double.dart
  Mobile/Carto/lib/views/widgets/form/form_fields/my_form_field_http_link.dart
  Mobile/Carto/lib/views/widgets/form/form_fields/my_form_field_int.dart
  Mobile/Carto/lib/views/widgets/form/form_fields/my_form_field_mail.dart
  Mobile/Carto/lib/views/widgets/form/form_fields/single_password_form_field.dart
  Mobile/Carto/lib/views/widgets/form/form_fields/username_form_field.dart
  Mobile/Carto/lib/views/widgets/form/games_form.dart
  Mobile/Carto/lib/views/widgets/form/general_form.dart
  Mobile/Carto/lib/views/widgets/form/opening_hour_form.dart
  Mobile/Carto/lib/views/widgets/form/other_fields/game_counter.dart
  Mobile/Carto/lib/views/widgets/form/other_fields/hour_piker.dart
  Mobile/Carto/lib/views/widgets/form/other_fields/my_checkbox_list_tile.dart
  Mobile/Carto/lib/views/widgets/form/other_fields/price_button.dart
  Mobile/Carto/lib/views/widgets/map_widget.dart
  Mobile/Carto/lib/views/widgets/tags.dart
  Mobile/Carto/lib/views/widgets/text.dart
Labels: documentation, refactor
